name: Build, Test & Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run ci:test

      - name: Clean Distribution Directory
        run: npm run ci:clean

      - name: Build Application
        run: npm run build

      - name: List Files in Distribution Directory
        run: ls -R ./dist

#      - name: FTP Deploy
#        uses: SamKirkland/FTP-Deploy-Action@3.1.1
#        with:
#          ftp-server: "${{ secrets.CD_FTP_SERVER }}"
#          ftp-username: "${{ secrets.CD_FTP_USERNAME }}"
#          ftp-password: "${{ secrets.CD_FTP_PASSWORD }}"
#          local-dir: "dist/"
