name: Build, Test & Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build

      - name: List Files in Distribution Directory
        run: ls -R ./dist

      - name: SSH Deploy
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ secrets.SERVER }}
          remote-user: ${{ secrets.USERNAME }}
          private-ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          source-path: ./dist/website_front_angular/
          destination-path: public_html/angular_portfolio/
