name: Install, Build & Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Install, Build & deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Installing Dependencies
        run: npm ci

      - name: Building Application
        run: npm run build

      - name: List Files in Distribution Directory
        run: ls -R ./dist

      - name: 📂 Sync Files
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: bertrandbouland.com
          remote-user: iwng4666
          private-ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          destination-path: ~/public_html/angular_portfolio/
          source-path: ./dist/website_front_angular/
